# Postgres - CalendarioLaboral
spring.datasource.url=jdbc:postgresql://localhost:5432/calendariolaboral
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# API Festivos (Express)
api.festivos.url=http://localhost:3000
